config/routes.rb
Rails.application.routes.draw do

  resources :companies

  resources :authors

  get 'video/index'

  resources :videos
  resources :categories
  resource :contacts
  resource :abouts
  resources :blogs
  resources :events
  resources :images
  resources :adverts
  resources :articles

  resource :companies do
    resources :events
  end

  resources :authors do
    resources :blogs
  end

  resources :categories do
    resources :articles
  end

  root 'base#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount ActiveAdmin::Tinymce::Engine => '/', as: 'admin_editor'

  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  def index
    @articles = Article.top_article
    @interesting = Article.interesting

    @events = Event.index_event

    @blogs = Blog.top_blog(Time.zone.now)

    @adverts_right = Advertising.right
    @adverts_top = Advertising.top
    @adverts_big = Advertising.big

    @videos = Video.top(Time.zone.now)

    set_meta_tags title: 'Лілія',
                  site: 'Лілія',
                  description: 'Інтернет-журнал про здоровя та життя Лілія',
                  og: {
                    url:  "http://liliia.com.ua",
                    type: 'website',
                    title: 'Лілія',
                    description: 'Інтернет-журнал про здоровя та життя Лілія',
                    image: URI.join(request.url, image_url('logo.png'))
                  }
  end
end

app/helpers/base_helper.rb
module BaseHelper
end

app/views/base/index.slim
.col-12
  .row
    .col-6.col-sm
      .interesting-block
        .header
          h5.text-center
            | Цікавинки
        .col-12
          -@interesting.each do |article_interest|
            .body
              .row
                .col-9
                  = link_to article_interest.category.name, category_path(article_interest.category), class: 'interesting-category'
                  h5
                    strong
                      = link_to truncate_html(article_interest.title, length: 50), article_path(article_interest)

                  =truncate_html(article_interest.body, length: 50)

                .col-3
                  = image_tag(article_interest.image.url, size: 120, class: 'rounded img-fluid')
            hr

    .col-6.col-xl-6
      - if @adverts_big.present?
        - @adverts_big.each do |big|
          a href="#{big.url}"
            = image_tag(big.image.url, class: 'img-fluid image-big')
      - else
        .adverts-big-stub
          h3.text-white.text-center Тут може бути ваша реклама

div style="padding-bottom:20px;"
.row
  .col-8.col-sm
    .col-12
      - @articles.each do |article|
        .jumbotron.jumbotron-fluid
          .row
            .col-10
              .row
                .col-10
                  h5
                    strong
                      = link_to article.title, article_path(article)

              .position-category-name
                =link_to article.category.name, category_path(article.category), class: 'category'

              =truncate_html(article.body, length: 90)

              .article-date
                = l(article.created_at, format: :long)

            .col-2
              = image_tag(article.image.url, class: 'rounded img-fluid')

  .col-4.col-xl-4
    .col-12
      - if @adverts_right.present?
        - @adverts_right.each do |advert|
          a href="#{advert.url}"
            = image_tag(advert.image.url, class: 'image-fluid pad image-right')
      - else
        .adverts-right-stub
          h3.text-center тут може бути ваша реклама
        br
        .adverts-right-stub
          h3.text-center тут може бути ваша реклама
        br
        .adverts-right-stub
          h3.text-center тут може бути ваша реклама


      h3.text-center style='margin-top:10px;' Топ відео
      - @videos.each do |video|
        iframe.video src="https://www.youtube.com/embed/#{video.uid}"  frameborder='0' allowfullscreen

//#### Blogs and Event ####//
.col-12 style="padding-bottom: 10px;"
  .row
    .col-5
      hr
    .col
      h5.text-center Блоги
    .col-5
      hr
  .blog
    .row
      - @blogs.each do |blog|
        .col-3
          .media
            =image_tag(blog.image.url(:thumb), size: 100, class: 'align-self-start mr-3')
            .media-body
              = link_to blog.author.name, author_path(blog.author), class: 'author-link' if blog.author.present?

              h5.mt-0
                = link_to truncate_html(blog.title.capitalize, length: 20), blog_path(blog)

              = truncate_html(blog.body, length: 25)

              =link_to 'Читати', blog_path(blog), class: 'position-link'



  .row style="margin-top: 20px;"
    .col-5
      hr
    .col
      h5.text-center Події
    .col-5
      hr

  .event
    .row
      - @events.each do |event|
        .col-3
          .media
            =image_tag(event.image.url(:thumb), size: 100, class: 'align-self-start mr-3')

            .media-body
              =link_to event.company.name, company_path(event.company), class: 'company-link'

              h5.mt-0
                = link_to truncate_html(event.title.capitalize, length: 20), event_path(event)

              = truncate_html(event.body, length: 20)
              = link_to 'Далі', event_path(event), class: 'position-link'