config/routes.rb
Rails.application.routes.draw do

  resources :companies

  resources :authors

  get 'video/index'

  resources :videos
  resources :categories
  resource :contacts
  resource :abouts
  resources :blogs
  resources :events
  resources :images
  resources :adverts
  resources :articles

  resource :companies do
    resources :events
  end

  resources :authors do
    resources :blogs
  end

  resources :categories do
    resources :articles
  end

  root 'base#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount ActiveAdmin::Tinymce::Engine => '/', as: 'admin_editor'

  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                 :integer          not null, primary key
#  title              :string
#  body               :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  published          :boolean
#  date               :datetime
#  company_id         :integer
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Event < ApplicationRecord
  extend FriendlyId

  has_attached_file :image, styles: { medium: '300x300>', blog: "295x191>", thumb: "100x100>" }, convert_options: { medium: "-quality 60 -interlace Plane", blog: "-quality 60 -interlace Plane" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :company

  scope :index_event, -> { where(published: true).limit(4) }
  default_scope { order(created_at: :desc) }

  validates :title, :body, presence: true

  friendly_id :title, use: :scoped, scope: :company
end

app/controllers/events_controller.rb
class EventsController < BaseController
  before_action :set_event, only: [:show]
  def index
    @events = Event.all.page(params[:page])
    @adverts = Advertising.page_event
  end

  def show
    set_meta_tags title: @event.title,
                  site: 'Лілія',
                  description: @event.body.html_safe,
                  og: {
                    url:  event_url(@event),
                    type: 'website',
                    title: @event.title,
                    description: @event.body.html_safe,
                    image: URI.join(request.url, @event.image.url)
                  }
  end

  private
    def set_event
      @event = Event.friendly.find(params[:id])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.slim
.col-12
  .row
    .col-8
      .row
        - @events.each do |event|
          .col
            .card.card-articles
              =image_tag(event.image.url, class: 'card-img-top card-img')
              .card-body
                .category
                  strong
                    = event.company.name
                h5.card-title
                  = link_to truncate_html(event.title, length: 30), event_path(event)
                .card-text
                  = truncate_html(event.body, length: 50)
                .row
                  .col-5
                    p.card-text
                      = link_to 'Далі', event_path(event)
                  .col-7
                    strong.date
                      =l(event.date, format: :long)

        .col-12
          .row
            .col-4
            .col
              = paginate @events, theme: 'twitter-bootstrap-4'
            .col-4
    .col-4
      - if @adverts.present?
        - @adverts.each do |advert|
          a href="#{advert.url}"
            = image_tag(advert.image.url, class: 'image-fluid pad image-right')
      - else
        .adverts-right-stub
          h3.text-center тут може бути ваша реклама
        br
        .adverts-right-stub
          h3.text-center тут може бути ваша реклама
        br
        .adverts-right-stub
          h3.text-center тут може бути ваша реклама

app/views/events/show.slim
.container
  .row
    .col-12
      .row
        h5
          strong= @event.title
      .row
        strong
          = l(@event.date, format: :long)
      .row
        p=@event.body.html_safe

      .row
        div
          = social_share_button_tag(@event.title, url: article_url(@event), desc: truncate_html(@event.body, length: 60), image: asset_url(@event.image.url, host: 'liliia.com.ua'))