config/routes.rb
Rails.application.routes.draw do

  resources :companies

  resources :authors

  get 'video/index'

  resources :videos
  resources :categories
  resource :contacts
  resource :abouts
  resources :blogs
  resources :events
  resources :images
  resources :adverts
  resources :articles

  resource :companies do
    resources :events
  end

  resources :authors do
    resources :blogs
  end

  resources :categories do
    resources :articles
  end

  root 'base#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount ActiveAdmin::Tinymce::Engine => '/', as: 'admin_editor'

  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/partials/_facebooksdk.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '2185085991718553',
      xfbml      : true,
      version    : 'v2.12'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/partials/_footer.slim
footer
  .col-12
    .row
      .col
        = image_tag('logo.png', width: '220', height: '145', class: 'footer-logo')
      .col-7
      .col.contacts


        = link_to "Наші Контакти", contacts_path, class: 'text-white'
        br
        = link_to "Про Нас", abouts_path, class: 'text-white'

    .row
      .container
        p.text-center.text-white style="font-size: 11px"
          | &copy;2018, «Лілія». Використання матеріалів сайту лише за умови посилання (для інтернет-видань - гіперпосилання) на «Лілію».

app/views/layouts/partials/_google_analytics.html.erb
<% if Rails.env == "production"  %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-113550144-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<% end %>

app/views/layouts/partials/_menu.slim
nav#header.navbar.navbar-expand-lg.navbar-light.bg-light.container-fluid
  =link_to image_tag('logo-top.png', size: 60, class: 'img-fluid'), root_path, class: 'navbar-brand'
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon

  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto.col-7
      li.nav-item.dropdown
        a.nav-link.dropdown-toggle.bolder href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" Рубрики

        - categories = Category.all
        / - subcategories = categories.first.children
        ul.dropdown-menu.multi-level role="menu" aria-labelledby="dropdownMenu"
          / li.dropdown-submenu
          li.nav-item
            - categories.each do |category|
              = link_to category.name, category_path(category), class: 'dropdown-item', tabindex: -1
              / ul.dropdown-menu
              /   - subcategories.each do |ch|
              /     li.dropdown-item
              /       = link_to ch.title, category_path(category.id), class:'dropdown-item', tabindex: -1

      li.nav-item
        = link_to 'Головна', root_path, class: 'nav-link bolder'

        li.nav-item
          = link_to 'Відео', videos_path, class: 'nav-link bolder'

      li.nav-item
        = link_to 'Події', events_path, class: 'nav-link bolder'

      li.nav-item
        = link_to 'Блог', blogs_path, class: 'nav-link bolder'

    ul.navbar-nav
      li.nav-item
        a.navabar-brand href="https://www.facebook.com/magazine.liliia/"
          = image_tag 'social-icons/facebook.png', class: 'rounded mt-2 social-img'
      li.nav-item
        a.navabar-brand href="https://www.instagram.com/magazine_liliia/"
          = image_tag 'social-icons/instagram.png', class: 'rounded mt-2 social-img'
      li.nav-item
        a.navabar-brand href="https://plus.google.com/u/0/105168718602761376408"
          =image_tag 'social-icons/google-plus.png', class: 'rounded mt-2 social-img'

app/views/layouts/partials/_top_baner.slim
- adverts_top = Advertising.top.reload
.top-baner
  .container
    - if adverts_top.present?
      - adverts_top.each do |advert_top|
        a href="#{advert_top.url}"
          = image_tag(advert_top.image.url, height: '100', class: 'img-fluid position')
    - else
      .adverts-stub.position
        h4.text-white.text-center style='padding-top: 30px;'
          | Тут може бути ваша реклама

app/views/layouts/partials/_top_menu.slim
.top-menu
  ul.nav.justify-content-center
    li
      a href="#{root_path}"
        = image_tag('logo.png', width: '220', height: '145')